config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about" , as: "about"
  # get "homes/about" => "homes#about", as: "about"

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  validates :title, presence: true
  validates :body,  presence: true, length: { maximum: 200}
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    # favorites.where(user_id: user.id).exists?
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20}, uniqueness: { case_sensitive: false }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about] 
  before_action :configure_permitted_parameters, if: :devise_controller?


def after_sign_in_path_for(resource)
  user_path(@user.id)
end
  
def after_sign_out_path_for(resource)
     root_path
end

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
end

def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) # 注目
end
#これ追加したら新規登録のemail blanckedが解消された

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # def new
  #   @book = Book.new
  # end

  def create
    @newbook = Book.new(book_params)
    @newbook.user_id = current_user.id
    # @newbook.save
    # flash[:notice] = "You have cteated new book successfully."
    # redirect_to book_path(@newbook.id)

    if @newbook.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@newbook.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    # @book = book_id
    @user = current_user
    @books = Book.all
    @newbook = Book.new
  end

  def edit
    # @book = Book.find(params[:id])
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    # @book.update(book_params)
    # flash[:notice] = "You have updated book successfully."
    # redirect_to book_path(@book.id)
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
   redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @users = User.all
    @newbook = Book.new
  end


  def show
    @user = User.find(params[:id])
    @books = @user.books
    @newbook = Book.new

    # @book = Book.new(book_params)
    # @book.user_id = current_user.id
    # @book.save
    # redirect_to books_path
  end

  def edit
    # @user = User.find(params[:id])
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    # @user.update(user_params)
    # flash[:notice] = "You have updated user successfully."
    # redirect_to user_path(@user.id)
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> errors occurred!</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_new.html.erb
  <div class="mt-5">
    <h2>New book</h2>
    <%= form_with model: @newbook do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
        <%= f.text_area :body %>
      <div class="mt-3">
        <p><%= f.submit 'Create Book', class: 'btn btn-success' %></P>
      </div>
    <% end %>
</div>

app/views/books/edit.html.erb
<div class="container mt-4">
    <h1 class="text-center">Editing Book</h1>
    <% if @book.errors.any? %>
        <div class="error">
          <h3><%= @book.errors.count %> errors occurred!</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li class="error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    
    <div class="row">
      <div class="col-xs-offset-3 col-xs-6">
        <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
          <h4>タイトル</h4>
          <%= f.text_field :title %>
          <h4>本文</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Update Book' %>
        <% end %>
        
        <div class="menu">
          <%= link_to "Show", book_path(@book.id) %>  | <a href="/books">Back</a>
        </div>
        
      </div>
    </div>
    
</div>

app/views/books/index.html.erb
<% if @newbook.errors.any? %>
    <div class="error">
      <h3><%= @newbook.errors.count %> errors occurred!</h3>
      <ul>
        <% @newbook.errors.full_messages.each do |message| %>
          <li class="error-message"><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>



<div class="container mt-4">
  <div class="row">

    <div class="col-md-3">
       <%= render 'users/user' %>
       <%= render 'books/new' %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="w-100">
        <thead class="border-top border-bottom border-seconddark">
          <tr>
            <th colspan="1"></th><th class="py-3">Title</th><th>Opinion</th><th colspan="4"></th>
          </tr>
        </thead>
        
        
        <% @books.each do |book| %>
        <tbody>
          <tr class="border-bottom border-seconddark">
            
            <td class="pt-4">
               <%= link_to user_path(book.user.id) do %>
                 <p><%= image_tag book.user.get_profile_image(100,100) %></p>
               <% end %>
            </td>
            
            <td>
                <%= link_to book_path(book.id) do %>
                <span><%= book.title %></span>
                <% end %>
            </td>
            
            <td>
              <span><%= book.body %></span>
            </td>
            
            <td>
              <%= render 'favorites/favorite', book: book %>
            </td>
            
            <td>
              <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
            </td>
          </tr>
        </tbody>
        <% end %>
        
        
      </table>
    </div>

    </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>


<h1>投稿フォーム</h1>
  <%= form_with model: @book do |f| %>
    <h4>タイトル</h4>
      <%= f.text_field :title %>
    <h4>本文</h4>
      <%= f.text_area :body %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/books/show.html.erb
<div class="container mt-4">
    <div class="row">

      <div class="col-md-3">
        <%= render 'users/user' %>
        <%= render 'books/new' %>
      </div>

      <div class="col-md-8 offset-md-1">
          <h1>Book detail</h1>
          <table class="w-100">
            <thead class="border-top border-bottom border-seconddark">
              <tr>
                <th colspan="1"></th><th>タイトル</th><th>本文</th><th colspan="4"></th><th colspan="5"></th><th colspan="6"></th><th colspan="7"></th>
              </tr>
            </thead>
            <tbody>
              <tr class="border-bottom border-seconddark">
                
                <td class="pt-4">
                   <%= link_to user_path(@book.user.id) do %>
                      <p><%= image_tag @book.user.get_profile_image(100,100) %></p>
                      <span><%= @book.user.name %></span>
                   <% end %>
                </td>
                
                <td><%= link_to @book.title, book_path(@book.id) %></td>
                
                <td><%= @book.body %></td>
                
                <td>
                   <%= render 'favorites/favorite', book: @book %>
                </td>
                
                <td>
                  コメント数:<%= @book.book_comments.count %>
                </td>
          
                <td>
                  <% if @book.user == current_user %>
                    <%= link_to 'Edit', edit_book_path(@book.id) %></td>
                  <% end %>
                <td>
                  <% if @book.user == current_user %>
                    <%= link_to 'Destroy', book_path(@book.id) , method: :delete %></td>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
          
          
          <div class="w-100">
             
                <% @book.book_comments.each do |book_comment| %>
                <p>
                    <%= image_tag book_comment.user.get_profile_image(100,100) %>
                    <%= link_to book_comment.user.name , user_path(@book.user.id)  %> 
                    <%= book_comment.comment %>
                    <% if book_comment.user == current_user %>
                    <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
                    <% end %>
                </p>
                <% end %>
             
             <p class="w-100">
                <%= form_with model: [@book, @book_comment] do |f| %>
                  <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" , :size => "50x6" %>
                    <P><%= f.submit "送信する" %></P>
                <% end %>
             </p>
             
          </div>
          
      </div>

    </div>
  </div>

app/views/favorites/_favorite.html.erb
<td>
      <% if book.favorited_by?(current_user) %>
        <%= link_to book_favorites_path(book), method: :delete do %>
         <i class="fas fa-heart"></i><%= book.favorites.count %> 
         <!--♥-->
        <% end %>
      
      <% else %>
        <%= link_to book_favorites_path(book), method: :post  do %>
         <i class="far fa-heart"></i> <%= book.favorites.count %>
          <!--<i class="far fa-heart"></i>-->
          <!--♡-->
        <% end %>
    <% end %>
</td>

app/views/homes/about.html.erb
<body>
    <div class="container">
            <h1 class="mt-3  text-center">Welcome to <i class="fas fa-book"></i>Bookers!</h1>
    </div>
</body>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="container">
    <h1 class="text-center mt-4">Welcome to <i class="fas fa-book"></i>Bookers!</h1>
    
    <div class="text-center">
      
        <p class"text-center mb-5">you can share and exchange your opinions , inpressions , and emotions<br>
           about various books!</p>
           
           
        <div class="mb-4">
           <div class="mb-4">
             <%= link_to("Log in", new_user_session_path, class: ' btn text-white bg-primary py-2 px-auto') %>
            </div>
           <div class="mb-4">
             <%= link_to("Sign up", new_user_registration_path, class: ' btn text-white bg-success py-2 px-7') %>
            </div>
        </div>   
        
        
    </div>
  </div>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header class=" bg-dark">
      <div class="container d-flex">

         <h1> <%= link_to('Bookers', root_path, class: 'text-white')%></h1>

             <nav class="nav ml-auto">

                  <% if user_signed_in? %>
                  <li class="nav-item mr-4 mt-3">
                     <%= link_to user_path(current_user.id) do %>
                       <i class="fas fa-home text-white"></i><span class="text-white"> Home</span>
                     <% end %>
                  </li>
                  <li class="nav-item mr-4 mt-3">
                     <%= link_to "/users" do %>
                       <i class="fas fa-users text-white"></i><span class="text-white"> Users</span>
                     <% end %>
                  </li>
                  <li class="nav-item mr-4 mt-3">
                     <%= link_to "/books" do %>
                       <i class="fas fa-book-open text-white"></i><span class="text-white" > Books</span>
                     <% end %>
                  </li>
                  <li class="nav-item mr-4 mt-3">
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <i class="fas fa-sign-out-alt text-white"></i><span class="text-white"> logout</span>
                      <% end %>
                  </li>

                  <% else %>
                    <li class="nav-item mr-4 mt-3">
                       <%= link_to root_path do %>
                        <i class="fas fa-home text-white"></i><span class="text-white"> Home</span>
                      <% end %>
                    </li>

                    <li class="nav-item mr-4 mt-3">
                      <%= link_to about_path do %>
                        <i class="fas fa-link text-white"></i><span class="text-white"> About</span>
                      <% end %>
                    </li>

                    <li class="nav-item mr-4 mt-3">
                      <%= link_to new_user_registration_path do %>
                        <i class="fas fa-user-plus text-white"></i><span class="text-white"> sign up</span>
                      <% end %>
                    </li>

                    <li class="nav-item mr-4 mt-3">
                      <%= link_to new_user_session_path do %>
                        <i class="fas fa-sign-in-alt text-white"></i><span class="text-white"> login</span>
                       <% end %>
                    </li>

                  <% end %>
             </nav>
       </div>
  </header>
  <body>
    <div>
     <%= flash[:notice] %>
    </div>
    <%= yield %>
  </body>

    <footer class="footer">
      <div class="container">
        <p class="text-center mb-0">CopyRight bookers</p>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user.html.erb
<h1>User info</h1>
<%= image_tag @user.get_profile_image(100,100) %>
  <h3>name: <%= @user.name %></h3>
  <h3>introduction: <%= @user.introduction %></h3>

  <%= link_to edit_user_path(@user.id) do %>
   <div class="btn border w-75"><i class="fas fa-user-cog "></i></div>
<% end %>

app/views/users/edit.html.erb
<div class="container mt-4">
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <h2 class="text-center">User info</h2>

    <% if @user.errors.any? %>
      <div class="error">
        <h3><%= @user.errors.count %> errors occurred!</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li class="error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
     <% end %>

      <%= form_with model: @user do |f| %>
      <p>
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName"%>
      </p>
      <p>
        <label for="inputImage">Image</label>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
      </p>
      <p>
        <label for="inputIntroduction">Introduction</label>
        <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction" %>
      </p>

      <%= f.submit "Update User" %>
      <% end %>
    </div>
</div>
</div>

app/views/users/index.html.erb
<div class="container mt-4">
  <div class="row">
  
    <div class="col-md-3">
       <%= render 'user' %>
       <%= render 'books/new' %>
    </div>

      <div class="col-md-8 offset-md-1">
          <h1>Users</h1>
          <table class="w-100">
            <thead class="border-top border-bottom border-seconddark">
              <tr>
                <th class="py-3">image</th><th>name</th><th colspan="3"></th>
              </tr>
            </thead>
            
            
            <% @users.each do |user| %>
            <tbody>
              <tr class="border-bottom border-seconddark">
                
                <td class="pt-4">
                  <%= link_to user_path(user.id) do %>
                    <p><%= image_tag user.get_profile_image(100,100) %></p>
                  <% end %>
                </td>
                
                <td><%= user.name %></td>
                
                <td><%= link_to 'Show', user_path(user.id) %></td>
                
              </tr>
            </tbody>
            <% end %>
          </table>
      </div>
    </div>
</div>

app/views/users/show.html.erb
 <div class="container mt-4">
    <div class="row">
      
        <div class="col-md-3">
          <%= render 'user' %>
          <%= render 'books/new' %>
        </div>


      <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="w-100">
        <thead class="border-top border-bottom border-seconddark">
          <tr>
            <th colspan="1"></th><th class="py-3">Title</th><th>Body</th><th colspan="4"></th><th colspan="5"></th>
          </tr>
        </thead>
        
        
        <% @books.each do |book| %>
        <tbody>
          <tr class="border-bottom border-seconddark">
            
            <td class="pt-4">
               <%= link_to user_path(book.user.id) do %>
                 <p><%= link_to image_tag book.user.get_profile_image(100,100) %></p>
               <% end %>
            </td>
            
            <td>
              <span>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
              </span>
            </td>
            
            <td><span><%= book.body %></span></td>
            
             <td>
              <%= render 'favorites/favorite', book: book %>
            </td>
            
            <td>
              <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
            </td>
            
          </tr>
        </tbody>
        <% end %>
      </table>
      </div>
      
      
    </div>
</div>